name: CI/CD - Docker Build & Deploy to EC2

on:
  push:
    branches: [ master ]

env:
  IMAGE_NAME: chisomjude/student-progress-tracker2

jobs:
  build-test-push-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Run container for test
      run: |
        docker run -d -p 8080:8080 \
          --name test_container \
          -e VAULT_ADDR="${{ secrets.VAULT_ADDR }}" \
          -e VAULT_ROLE_ID="${{ secrets.VAULT_ROLE_ID }}" \
          -e VAULT_SECRET_ID="${{ secrets.VAULT_SECRET_ID }}" \
          $IMAGE_NAME:latest

        for i in {1..10}; do
          curl --fail http://localhost:8080/health && break || sleep 2
        done

        docker logs test_container
        docker stop test_container
        docker rm test_container

    - name: Push image to Docker Hub
      run: docker push $IMAGE_NAME:latest

    - name: Deploy on EC2 via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          docker pull $IMAGE_NAME:latest
          docker stop student-progress-tracker2 || true && docker rm student-progress-tracker2 || true
          docker run -d -p 8080:8080 --name student-progress-tracker2 \
            -e VAULT_ADDR="${{ secrets.VAULT_ADDR }}" \
            -e VAULT_ROLE_ID="${{ secrets.VAULT_ROLE_ID }}" \
            -e VAULT_SECRET_ID="${{ secrets.VAULT_SECRET_ID }}" \
            $IMAGE_NAME:latest